//Date object
d=Date()
console.log("Date=",d)
d=new Date()
m=d.getMonth()+1
console.log(m)
d=new Date()
y=d.getFullYear()
console.log(y)
d=new Date()
x=d.getDay()+1
console.log(x)
d=new Date()
h=d.getHours()
console.log(h)
d=new Date()
m=d.getMinutes()
console.log(m)
d=new Date()
s=d.getSeconds()
console.log(s)
date=new Date()
var h=date.getHours()
var m=date.getMinutes()
var s=date.getSeconds()
console.log("Hours=",h)
console.log("Minutes",m)
console.log("Seconds=",s)